### ISSUE TITLE
mappling multiple frames at once

### ISSUE THREAD

**Issue by babinch** [votca/ctp#81]
Hi 

I have tried to load 10 frame trajectories by ctp_map -t topol.tpr -c trj.gro -s map.xml -f state.sql

While trj.gro file has 10 frames, only one frame can be loaded.
I tried to use --nframes 10 and it seems not working
also tried xml with <nframes>10</nframes> many spots.

What am I missing? 

Ubuntu Server 14.04 LTS
Gromacs 5.1.1 (single precision with GPU support)
built with votca buildutil

**Comment by 12AngryMen** [comment]
to my knowledge votca-ctp does not support loading more than one frame. We
normaly make different sql files for the individual frames.

Cheers Jens

2015-11-29 18:57 GMT+01:00 babinch <notifications@github.com>:
