### ISSUE TITLE
Cleanup the manual and merge into the main repository

### ISSUE THREAD

**Issue by crionez** [votca/ctp#95]
installation should compile the manual and install it into manuals folder of VOTCA

**Comment by junghans** [comment]
`ctp-manual` has been converted to CMake yet, but the manual in `xtp` should have all the pieces.

**Comment by junghans** [comment]
I think the manual should not be build by default due to all the latex dependencies, so something like:
```
 option(BUILD_CTP_MANUAL "Build ctp-manual" OFF)
if(BUILD_CTP_MANUAL)
  add_subdirectory(manual)
endif()
```
would be good.

**Comment by crionez** [comment]
@junghans: you can delete the ctp-manual repository

**Comment by junghans** [comment]
I fixed the first two in 0b8002eade84f9ede45cac9b349e5ea31ec903a6 and votca/buildenv#15

**Comment by crionez** [comment]
Ok. Had a look at it. No clue what to modify ;) Any hints?

**Comment by junghans** [comment]
I will make a PR later today.

**Comment by junghans** [comment]
See votca/votca#60

**Comment by junghans** [comment]
In https://travis-ci.org/votca/ctp/jobs/368294348 we get:
```
[  1%] Generating calculator_refs
cd /home/votca/votca/build/ctp/manual && ../../../ctp/manual/scripts/extract_calculators.sh /home/votca/votca/build/ctp/manual/reference/calculators.tex
[91m../../../ctp/manual/scripts/extract_calculators.sh: line 3: csg_call: command not found
[0m[91mmake[2]: *** [ctp/manual/CMakeFiles/ctp-manual_pdf.dir/build.make:133: ctp/manual/calculator_refs] Error 127
[0mmake[2]: Leaving directory '/home/votca/votca/build'
```
I guess the manual needs to depend `csg_call` being build first and then used from build directory.

**Comment by junghans** [comment]
I half-assed something together in #97.

**Comment by junghans** [comment]
Deploy works: http://doc.votca.org/ctp-manual.pdf

This pdf will get updated every time, you update the ctp submodule in votca/votca.
